spring.application.name: fingerprint_backend
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fingerprint_db?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://database-fingerprint.cz8mmu2gowqc.ap-northeast-2.rds.amazonaws.com:3306/fingerprint_db?serverTimezone=Asia/Seoul
    username: kyumin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    google:
      clientId: 441788767782-183ndebp7adg7dsigjqofpj56bb7c3mp.apps.googleusercontent.com

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true