spring.application.name: fingerprint_backend
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/fingerprint_db?serverTimezone=Asia/Seoul
    url: jdbc:mysql://database-fingerprint.cz8mmu2gowqc.ap-northeast-2.rds.amazonaws.com:3306/fingerprint_db?serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true